require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'Gemfile'
    - 'config.ru'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/bundle/**/*'
    - 'coverage/*'

  TargetRubyVersion: 2.6.3

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Style/MixinUsage:
  Enabled: false

Rails:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 8

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

Metrics/AbcSize:
  Max: 50
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false